#!/usr/bin/env zsh

# Navigation
alias ..=' cd .. '
alias ...=' cd ../../ '
alias popd=' popd -q '
alias pushd=' pushd -q '
alias stack=' dirs -v '

# Utilities
alias df=' df --human-readable --exclude-type=squashfs --exclude-type=tmpfs --exclude-type=devtmpfs --print-type '
alias now=" date +'%Y-%m-%d %H:%M:%S' "

# Git workflow
alias gcw=' ax git wip finish '
alias grw=' ax git wip drop '
alias guh=' Update-GitWIPBranchHistory '
alias gus=' ax git stable sync '
alias gwb=' ax git wip start '

# Editor variants (light theme)
alias manw='MANWIDTH="" command man '
alias nvim=' nvim '
alias hx=' hx '

# Help and logs (bat guaranteed by Home Manager)
alias help=' ax help '
alias h=' ax help '
alias follow=' Read-Log '
alias bat=' bat --paging=auto '
compdef _tail Read-Log

[[ -x $(command -v fzf-tmux) ]] && \
    alias fzf=' fzf-tmux --height 40% --reverse --preview "bat --color=always {}" '

alias fx=' Open-File '

man() {
    local __AX_WIDTH="$(( COLUMNS > 93 ? 90 : COLUMNS - 3 ))"
    for arg in "$@"; do
        case "$arg" in
            -k|-f|-K|--apropos|--whatis) command man "$@"; return ;;
        esac
    done
    local __AX_PAGE
    __AX_PAGE=$(command man -w "$@") || return $?
    mandoc -T utf8 -O width="${__AX_WIDTH}" ${(f)__AX_PAGE} | col -b | bat --style=plain --language=man
}

# ZFS (z prefix)
if [[ -x $(command -v zfs) ]] {
    alias lszsnap=' ax zfs snapshot list '
    alias rmzsnap=' Remove-ZfsSnapshot '
}

# Tools guaranteed by Home Manager
alias duf=' duf --hide special '
alias gh=' gh '
alias tokei=' tokei --exclude .github --exclude .git --sort code '
alias tree=' tree --dirsfirst '

# Optional tools (guard needed)
[[ -x $(command -v nvidia-settings) ]] && alias lscuda=' nvidia-settings -q CUDACores -t '


alias -s {asc,cs,dart,erl,ex{s},fs,htm{l},java,json,py,rebar,rs,scala,txt,xml}=nvim
alias -s {pdf,ps}=evince


alias -g B="| bat --paging=auto - "
alias -g C="| wc --lines - "
alias -g G="| grep "
alias -g H="| hx - "
alias -g L="| less --line-numbers "
alias -g R="| rg "
alias -g S="| sed --expression "
alias -g V="| nvim - "
