#! /usr/bin/env zsh

# Find-DockerImages: Search for Docker images by name pattern

[[ "$1" == "--help" ]] && echo "Usage: ${0:t} <search-term> - Search Docker Hub for images" && return 0

if [[ $# -lt 1 ]]; then
  echo "Usage: ${0:t} <search-term>"
  return 1
fi

# Join all arguments into a single search term
search_term="$*"
echo "Searching for Docker images matching: '$search_term'"

docker search "${search_term}" --format '{{.Name}} {{.StarCount}}' \
| awk -F'/' '{print $1, $2, $3}' \
| sort -k1,1 -k3,3nr \
| awk '{printf "%s/%s %s\n", $1, $2, $3}' \
| column -t
