#! /usr/bin/env zsh

# find-asdfplugin: Find an asdf plugin by name or pattern

# Variables --------------------------------------------------------------------
local _synopsis="Synopsis:
    ${0:t} <PLUGIN_NAME>

See also:
    ${0:t} --help
"
local _help="Description:
    Find an asdf plugin by name.

Usage:
    ${0:t} <PLUGIN_NAME>

Options:
    --help      Show this help message.

Examples:
    find-asdfplugin elixir
    find-asdfplugin uv
    find-asdfplugin
"


# Functions --------------------------------------------------------------------
_synopsis() {
    echo "${_synopsis}" | tail --lines=+2
}

_help() {
    echo "${_help}" | tail --lines=+2
}


# Options ----------------------------------------------------------------------
while [[ $# -gt 0 ]]; do
    case "$1" in
        --help)     _help_flag=true ;;
        *)          _arg=$1         ;;
    esac
    shift
done


# Main -------------------------------------------------------------------------
[[ -n $_help_flag ]] && _help && exit 0


# Driver -----------------------------------------------------------------------
function find_asdfplugin() {
    if command -v asdf > /dev/null 2>&1
    then
        local _plugin_name=${_arg} && [[ -z ${_plugin_name} ]] && _plugin_name=""
        asdf plugin list all | grep "^${_plugin_name}"
        printf "\n"
    else
        echo "asdf is not installed."
    fi
}


find_asdfplugin


unfunction _synopsis
unfunction _help
unfunction find_asdfplugin
