#! /usr/bin/env zsh

# Get-VideoFormat: Display video codec format

[[ "$1" == "--help" ]] && echo "Usage: ${0:t} <file>" && return 0

if [[ $# -lt 1 ]]; then
  echo "Error: Missing video file argument"
  return 1
fi

local _file="$1"
ffprobe -v error -select_streams v:0 -show_entries stream=codec_name -of default=noprint_wrappers=1:nokey=1 ${_file} 2>/dev/null
