#! /usr/bin/env zsh

# Get-Attributes: List all extended file system attributes for a file

source "${0:h}/../lib/output.zsh"
source "${0:h}/../lib/validation.zsh"

# option parsing ---------------------------------------------------------------
if [[ "$1" == "-h" || "$1" == "--help" ]]; then
    cat << EOF
Usage: ${0:t} <path>

List all attributes on a file or directory.

Options:
    -h, --help    Show this help message

Arguments:
    <path>       The path to the file or directory.

Examples:
    ${0:t} /path/to/file
    ${0:t} /path/to/directory
EOF
    return 0
fi

local _path=""

while [[ $# -gt 0 ]]; do
    case "$1" in
        -h|--help)    return 0 ;;
        --)           shift; break ;;
        -*)           __ax_error "Unknown option: $1"; return 1 ;;
        *)
            if [[ -z "${_path}" ]]; then
                _path="$1"
            else
                __ax_error "Too many arguments"
                return 1
            fi
            ;;
    esac
    shift
done


# checks -----------------------------------------------------------------------
__ax_require_arg "${_path}" "path" || { echo "${_help}"; return 1; }
__ax_check_deps getfattr || return 2
__ax_require_path_target "${_path}" || return 1


# main -------------------------------------------------------------------------
getfattr --dump "${_path}"
