#! /usr/bin/env zsh

# Get-GitHubGitIgnores: List available GitHub gitignore templates

[[ "$1" == "--help" ]] && echo "Usage: ${0:t}" && return 0

curl -s -H "Accept: application/vnd.github+json" \
    -H "X-GitHub-Api-Version: 2022-11-28" \
    https://api.github.com/gitignore/templates \
    | jq -r '.[]' \
    | awk 'BEGIN{print "Language"; print "---------------------------"} {print}' \
    | less -R
