#! /usr/bin/env zsh

# Get-DockerDanglingVolumes: List all dangling Docker volumes

source "${0:h}/../lib/output.zsh"
source "${0:h}/../lib/validation.zsh"

# Variables --------------------------------------------------------------------
local _synopsis="Synopsis:
    ${0:t}

See also:
    ${0:t} --help
"
local _help="Description:
    Get all dangling Docker volumes (volumes not attached to any container).

Usage:
    ${0:t}

Options:
    --help      Show this help message.

Examples:
    get-dockerdanglingvolumes
"


# Functions --------------------------------------------------------------------
_synopsis() {
    echo "${_synopsis}" | tail --lines=+2
}

_help() {
    echo "${_help}" | tail --lines=+2
}


# Options ----------------------------------------------------------------------
local _raw_flag=""

while [[ $# -gt 0 ]]; do
    case "$1" in
        --help)     _help_flag=true ;;
        --raw)      _raw_flag="--raw" ;;
        *)          _arg=$1         ;;
    esac
    shift
done


# Main -------------------------------------------------------------------------
[[ -n $_help_flag ]] && _help && return 0
__ax_check_deps docker || return 2


# Driver -----------------------------------------------------------------------
function get_dockerdanglingvolumes() {
    local _data
    _data=$(docker volume list --filter="dangling=true" --format="{{.Driver}}|{{.Name}}")

    if [[ -z "$_data" ]]; then
        echo "No dangling volumes found."
        return 0
    fi

    echo ""
    echo -e "Driver|Volume Name\n${_data}" | __ax_table $_raw_flag
    echo ""
}


get_dockerdanglingvolumes


unfunction _synopsis
unfunction _help
unfunction get_dockerdanglingvolumes
