#! /usr/bin/env zsh

# Get-SystemInformation: Display system information using fastfetch

[[ "$1" == "--help" ]] && echo "Usage: ${0:t}" && return 0

if ! command -v fastfetch &> /dev/null; then
    echo "fastfetch could not be found"
    return 1
fi

fastfetch
