#! /usr/bin/env zsh

# Get-Verb: Display PowerShell-style approved verbs for function naming

source "${0:h}/../lib/output.zsh"
source "${0:h}/../lib/validation.zsh"

# Variables --------------------------------------------------------------------
local _self="${0:A}"
local _synopsis="
Synopsis:
    ${_self} [opts]

See also:
    ${_self} --help
"
local _help="
Usage:
    ${0:t} [opts]

Description:
    Get the approved verb list of PowerShell.

Options:
    --help          Show this help message.
    --group         Show the verbs grouped by category.

Examples:
    ${_self} --group
"
local _grouped_verbs="
Common
    Add Clear Close Copy Enter Exit Find Format Get Hide Join Lock Move New Open
    Optimize Push Pop Redo Remove Rename Reset Resize Search Select Set Show
    Skip Split Step Switch Undo Unlock Watch
Communications
    Connect Disconnect Read Receive Send Write
Data
    Backup Checkpoint Compare Compress Convert ConvertFrom ConvertTo Dismount
    Edit Expand Export Group Import Initialize Limit Merge Mount Out Publish
    Restore Save Sync Unpublish Update
Diagnostic
    Debug Measure Ping Repair Resolve Test Trace
Lifecycle
    Approve Assert Build Complete Confirm Deny Deploy Disable Enable Install
    Invoke Register Request Restart Resume Start Stop Submit Suspend Uninstall
    Unregister Wait
Other
    Use
Security
    Block Grant Protect Revoke Unblock Unprotect
"


# Functions --------------------------------------------------------------------
_synopsis() {
    echo "${_synopsis}" | tail --lines=+2
}

_help() {
    echo "${_help}" | tail --lines=+2
}

_group() {
    echo "${_grouped_verbs}" | tail --lines=+2
}

# Options ----------------------------------------------------------------------
local _help_flag=""
local _group_flag=""

while [[ $# -gt 0 ]]; do
    case "$1" in
        -h|--help) _help_flag=true ;;
        --group)   _group_flag=true ;;
        --)        shift; break ;;
        -*)        __ax_error "Unknown option: $1"; return 1 ;;
        *)         __ax_error "Unexpected argument: $1"; return 1 ;;
    esac
    shift
done


# Main -------------------------------------------------------------------------
[[ -n $_help_flag ]] && _help && return 0

if [[ -n $_group_flag ]]; then
    _group
    return 0
fi

_group && return 0


# Unset ------------------------------------------------------------------------
unfunction _group
unfunction _help
unfunction _synopsis
