#! /usr/bin/env zsh

# Get-DanglingDockerImages: List all dangling Docker images

source "${0:h}/../lib/output.zsh"

# Variables --------------------------------------------------------------------
local _synopsis="Synopsis:
    ${0:t}

See also:
    ${0:t} --help
"
local _help="Description:
    Get all dangling docker images.

Usage:
    ${0:t}

Options:
    --help      Show this help message.

Examples:
    get-dockerdanglingimage
"


# Functions --------------------------------------------------------------------
_synopsis() {
    echo "${_synopsis}" | tail --lines=+2
}

_help() {
    echo "${_help}" | tail --lines=+2
}


# Options ----------------------------------------------------------------------
local _raw_flag=""

while [[ $# -gt 0 ]]; do
    case "$1" in
        --help)     _help_flag=true ;;
        --raw)      _raw_flag="--raw" ;;
        *)          _arg=$1         ;;
    esac
    shift
done


# Main -------------------------------------------------------------------------
[[ -n $_help_flag ]] && _help && return 0


# Driver -----------------------------------------------------------------------
function get_dockerdanglingimage() {
    local _header="Repository|Tag|Created|Size|ID"
    local _image=$(docker image list --format="{{.Repository}}|{{.Tag}}|{{.CreatedSince}}|{{.Size}}|{{.ID}}" --filter="dangling=true" | sort)
    echo ""
    echo -e "${_header}\n${_image}" | __ax_table $_raw_flag
    echo ""
}


get_dockerdanglingimage


unfunction _synopsis
unfunction _help
unfunction get_dockerdanglingimage
