#! /usr/bin/env zsh

# mount-conda: Mount and activate a conda environment

# Variables --------------------------------------------------------------------
local _synopsis="Synopsis:
    ${0:t}

See also:
    ${0:t} --help
"
local _help="Description:
    Activate the conda environment in the current shell.

Usage:
    ${0:t}

Options:
    --help      Show this help message.

Examples:
    ${0:t}
"


# Functions --------------------------------------------------------------------
_synopsis() {
    echo "${_synopsis}" | tail --lines=+2
}

_help() {
    echo "${_help}" | tail --lines=+2
}


# Options ----------------------------------------------------------------------
while [[ $# -gt 0 ]]; do
    case "$1" in
        --help)     _help_flag=true ;;
        *)          _arg=$1         ;;
    esac
    shift
done


# Main -------------------------------------------------------------------------
[[ -n $_help_flag ]] && _help && exit 0


# Driver -----------------------------------------------------------------------
function mount_conda() {
    if [[ -x "${HOME}/.anaconda3/bin/conda" ]] {
        export CONDA_AUTO_ACTIVATE_BASE=false
        __conda_setup="$('${HOME}/.anaconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
        if [[ $? -eq 0 ]] {
            eval "$__conda_setup"
        } else {
            if [[ -f "${HOME}/.anaconda3/etc/profile.d/conda.sh" ]] {
                source "${HOME}/.anaconda3/etc/profile.d/conda.sh"
            } else {
                path=("${HOME}/.anaconda3/bin" $path)
            }
        }
        unset __conda_setup
    } else {
        echo "Error: Conda not found in ${HOME}/.anaconda3/bin/conda"
    }
}


mount_conda


unfunction _synopsis
unfunction _help
unfunction mount_conda
