#! /usr/bin/env zsh

# new-condaenvironment: Create a new conda environment with specified packages

# _dry_run=false
if [[ $1 == "--dry-run" ]]; then
    _dry_run=true
    shift
fi

synopsis() {
    echo "Usage: ${0:t} [--dry-run]"
}

# _name=""
read_name() {
    echo "Name of the conda environment: "
    read -r _name

    if [[ -z ${_name} ]]; then
        echo "Name of the conda environment is required"
        synopsis
        exit 1
    fi
}

# _version=""
read_version() {
    echo "PyTorch CUDA version: "
    read -r _version

    if [[ -z ${_version} ]]; then
        echo "PyTorch CUDA version is required"
        synopsis
        exit 1
    fi

    if [[ ! ${_version} =~ ^[0-9]+\.[0-9]+(\.[0-9]+)?$ ]]; then
        echo "The version is not in semver format"
        synopsis
        exit 1
    fi
}

create_conda_environment() {
    local _options=(
       "--name ${_name}"
       "--channel pytorch"
       "--channel nvidia"
       "pytorch"
       "torchvision"
       "torchaudio"
       "pytorch-cuda=${_version}"
    )

    if $_dry_run; then
        conda create --dry-run ${_options[@]}
    else
        conda create ${_options[@]}
    fi
}

read_name
read_version
create_conda_environment "$@"

unset _dry_run
unset _name
unset _version
