#! /usr/bin/env zsh

# Read-DockerLog: Read and follow Docker container logs

source "${0:h}/../lib/output.zsh"
source "${0:h}/../lib/validation.zsh"

# Variables --------------------------------------------------------------------
local _synopsis="Synopsis:
    ${0:t} [opts] <CONTAINER_NAME>

See also:
    ${0:t}
"
local _help="Description:
    Reads the output of docker container log.

Usage:
    ${0:t} <CONTAINER_NAME>

Options:
    --help      Show this help message.

Examples:
    read-dockerlog <CONTAINER_NAME>
"


# Functions --------------------------------------------------------------------
_synopsis() {
    echo "${_synopsis}" | tail --lines=+2
}

_help() {
    echo "${_help}" | tail --lines=+2
}


# Options ----------------------------------------------------------------------
while [[ $# -gt 0 ]]; do
    case "$1" in
        --help)     _help_flag=true ;;
        *)          _arg=$1         ;;
    esac
    shift
done


# Main -------------------------------------------------------------------------
[[ -n $_help_flag ]] && _help && return 0
__ax_require_arg "$_arg" "container name" || { _synopsis; return 1; }
__ax_check_deps docker || return 2


# Driver -----------------------------------------------------------------------
function read_dockerlog() {
    docker logs "${_arg}" 2>&1
}


read_dockerlog "${_arg}"


unfunction _synopsis
unfunction _help
unfunction read_dockerlog
