#! /usr/bin/env zsh

# Remove-DockerDanglingImages: Remove all dangling Docker images

# Variables --------------------------------------------------------------------
local _synopsis="Synopsis:
    ${0:t}

See also:
    ${0:t} --help
"
local _help="Description:
    Remove all dangling Docker images (images without a tag).

Usage:
    ${0:t}

Options:
    --help      Show this help message.

Examples:
    remove-dockerdanglingimages
"


# Functions --------------------------------------------------------------------
_synopsis() {
    echo "${_synopsis}" | tail --lines=+2
}

_help() {
    echo "${_help}" | tail --lines=+2
}


# Options ----------------------------------------------------------------------
while [[ $# -gt 0 ]]; do
    case "$1" in
        --help)     _help_flag=true ;;
        *)          _arg=$1         ;;
    esac
    shift
done


# Main -------------------------------------------------------------------------
[[ -n $_help_flag ]] && _help && return 0


# Driver -----------------------------------------------------------------------
function remove_dockerdanglingimages() {
    local _ids=$(docker image list --filter="dangling=true" --format="{{.ID}}")

    if [[ -z "${_ids}" ]]; then
        echo "No dangling images to remove."
        return 0
    fi

    echo "${_ids}" | while read -r _id; do
        echo "Removing image: ${_id}"
        docker rmi "${_id}"
    done
}


remove_dockerdanglingimages


unfunction _synopsis
unfunction _help
unfunction remove_dockerdanglingimages
