#! /usr/bin/env zsh

# Remove-ZfsSnapshot: Remove a ZFS snapshot using zsysctl

source "${0:h}/../lib/output.zsh"
source "${0:h}/../lib/validation.zsh"

# Options/Arguments ---------------------------------------------------------
if [[ "$1" == "-h" || "$1" == "--help" ]]; then
    cat << EOF
Usage: ${0:t} <snapshot-name>

Description:
    Remove a ZFS snapshot using zsysctl state remove.
    Requires the snapshot name as an argument.

Options:
    -h, --help    Show this help message

Arguments:
    snapshot      The name of the snapshot to remove

Examples:
    ${0:t} autozsys_abc123
EOF
    return 0
fi

local _snapshot=""
while [[ $# -gt 0 ]]; do
    case "$1" in
        *)          _snapshot=$1    ;;
    esac
    shift
done


# Main -------------------------------------------------------------------------
__ax_require_arg "${_snapshot}" "snapshot name" || return 1
__ax_check_deps zsysctl || return 2


# Driver -----------------------------------------------------------------------
function remove_zfssnapshot() {
    zsysctl state remove "${1}" --system
    printf "\n"
}


remove_zfssnapshot "${_snapshot}"
