#! /usr/bin/env zsh

# Remove-Attribute: Remove extended file system attribute from a file

source "${0:h}/../lib/output.zsh"
source "${0:h}/../lib/validation.zsh"

# variables --------------------------------------------------------------------
local _self="${0}"
local _help="
synopsis: ${_self} <attribute> <path>
    Remove an attribute on a file or directory.

options:
    -h, --help     Show this help message and exit.
    -v, --version  Show version information and exit.

arguments:
    <attribute>  The attribute to remove.
    <path>       The path to the file or directory.

example:
    remove-attribute user.comment /path/to/file
    remove-attribute user.app.name /path/to/directory
"
local _version="0.7.1"


# functions --------------------------------------------------------------------
function _show_help() {
    echo "${_help}" | tail --lines=+2
}

function _show_version() {
    echo "${_version}"
}


# option parsing ---------------------------------------------------------------
local _attribute=""
local _path=""
local _help_flag=""
local _version_flag=""

while [[ $# -gt 0 ]]; do
    case "$1" in
        -h|--help)    _help_flag=true ;;
        -v|--version) _version_flag=true ;;
        --)           shift; break ;;
        -*)           __ax_error "Unknown option: $1"; return 1 ;;
        *)
            if [[ -z "${_attribute}" ]]; then
                _attribute="$1"
            elif [[ -z "${_path}" ]]; then
                _path="$1"
            else
                __ax_error "Too many arguments"
                echo "${_help}"
                return 1
            fi
            ;;
    esac
    shift
done


# option actions ---------------------------------------------------------------
[[ -n "${_help_flag}" ]] && echo "${_help}" && return 0
[[ -n "${_version_flag}" ]] && echo "${_version}" && return 0


# checks -----------------------------------------------------------------------
__ax_require_arg "${_attribute}" "attribute" || { echo "${_help}"; return 1; }
__ax_require_arg "${_path}" "path" || { echo "${_help}"; return 1; }
__ax_check_deps setfattr || return 2
[[ ! -e "${_path}" ]] && { __ax_error "Path does not exist."; return 1; }
[[ ! -w "${_path}" ]] && { __ax_error "Path is not writable."; return 1; }
[[ ! -d "${_path}" && ! -f "${_path}" ]] && { __ax_error "Path is not a file or directory."; return 1; }


# main -------------------------------------------------------------------------
setfattr --remove user."${_attribute}" "${_path}"


# cleanup ----------------------------------------------------------------------
unfunction _show_version
unfunction _show_help

