#! /usr/bin/env zsh

# Remove-Attribute: Remove extended file system attribute from a file

source "${0:h}/../lib/output.zsh"
source "${0:h}/../lib/validation.zsh"

# option parsing ---------------------------------------------------------------
if [[ "$1" == "-h" || "$1" == "--help" ]]; then
    cat << EOF
Usage: ${0:t} <attribute> <path>

Remove an attribute on a file or directory.

Options:
    -h, --help    Show this help message

Arguments:
    <attribute>  The attribute to remove.
    <path>       The path to the file or directory.

Examples:
    ${0:t} user.comment /path/to/file
    ${0:t} user.app.name /path/to/directory
EOF
    return 0
fi

local _attribute=""
local _path=""

while [[ $# -gt 0 ]]; do
    case "$1" in
        -h|--help)    return 0 ;;
        --)           shift; break ;;
        -*)           __ax_error "Unknown option: $1"; return 1 ;;
        *)
            if [[ -z "${_attribute}" ]]; then
                _attribute="$1"
            elif [[ -z "${_path}" ]]; then
                _path="$1"
            else
                __ax_error "Too many arguments"
                return 1
            fi
            ;;
    esac
    shift
done


# checks -----------------------------------------------------------------------
__ax_require_arg "${_attribute}" "attribute" || { echo "${_help}"; return 1; }
__ax_require_arg "${_path}" "path" || { echo "${_help}"; return 1; }
__ax_check_deps setfattr || return 2
__ax_require_writable_path_target "${_path}" || return 1
__ax_require_xattr_name "${_attribute}" || return 1


# main -------------------------------------------------------------------------
setfattr --remove user."${_attribute}" "${_path}"
