#! /usr/bin/env zsh

# Set-Attribute: Set extended file system attribute on a file

source "${0:h}/../lib/output.zsh"
source "${0:h}/../lib/validation.zsh"

# variables --------------------------------------------------------------------
local _self="${0:A}"
local _help="
synopsis: ${_self} <attribute> <value> <path>
    Set an attribute on a file or directory.

options:
    -h, --help     Show this help message and exit.
    -v, --version  Show version information and exit.

arguments:
    <attribute>  The attribute to set.
    <value>      The value to set the attribute to.
    <path>       The path to the file or directory.

example:
    set-attribute user.comment \"This is a test\" /path/to/file
    set-attribute user.app.name \"MyApp\" /path/to/directory
"
local _version="0.7.1"


# functions --------------------------------------------------------------------
function _show_help() {
    echo "${_help}" | tail --lines=+2
}

function _show_version() {
    echo "${_version}"
}


# option parsing ---------------------------------------------------------------
local _attribute=""
local _value=""
local _path=""
local _help_flag=""
local _version_flag=""

while [[ $# -gt 0 ]]; do
    case "$1" in
        -h|--help)    _help_flag=true ;;
        -v|--version) _version_flag=true ;;
        --)           shift; break ;;
        -*)           __ax_error "Unknown option: $1"; return 1 ;;
        *)
            if [[ -z "${_attribute}" ]]; then
                _attribute="$1"
            elif [[ -z "${_value}" ]]; then
                _value="$1"
            elif [[ -z "${_path}" ]]; then
                _path="$1"
            else
                __ax_error "Too many arguments"
                echo "${_help}"
                return 1
            fi
            ;;
    esac
    shift
done


# option actions ---------------------------------------------------------------
[[ -n "${_help_flag}" ]] && echo "${_help}" && return 0
[[ -n "${_version_flag}" ]] && echo "${_version}" && return 0


# checks -----------------------------------------------------------------------
__ax_require_arg "${_attribute}" "attribute" || { echo "${_help}"; return 1; }
__ax_require_arg "${_value}" "value" || { echo "${_help}"; return 1; }
__ax_require_arg "${_path}" "path" || { echo "${_help}"; return 1; }
__ax_check_deps setfattr || return 2
[[ ! -e "${_path}" ]] && { __ax_error "Path does not exist."; return 1; }
[[ ! -w "${_path}" ]] && { __ax_error "Path is not writable."; return 1; }
[[ ! -d "${_path}" && ! -f "${_path}" ]] && { __ax_error "Path is not a file or directory."; return 1; }
[[ ! "${_attribute}" =~ ^[a-zA-Z0-9._-]+$ ]] && { __ax_error "Invalid attribute name."; return 1; }


# main -------------------------------------------------------------------------
setfattr --name user."${_attribute}" --value "${_value}" "${_path}"


# cleanup ----------------------------------------------------------------------
unfunction _show_version
unfunction _show_help

