#! /usr/bin/env zsh

# Show-GitHubGitIgnore: Show GitHub gitignore template for a specific language

source "${0:h}/../lib/output.zsh"
source "${0:h}/../lib/validation.zsh"

[[ "$1" == "--help" ]] && echo "Usage: ${0:t} [language]" && return 0

__ax_check_deps curl jq || return 2

LANGUAGE=${1:-Python}
curl -s -H "Accept: application/vnd.github+json" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
  https://api.github.com/gitignore/templates/${LANGUAGE} | jq -r '.source'
