#!/usr/bin/env zsh

# Start-DockerAzureCli: Start Azure CLI in Docker

[[ "$1" == "--help" ]] && echo "Usage: ${0:t} - Start Azure CLI container with persistent volume" && return 0

source "${0:h}/../lib/docker.zsh"

local __AX_NAME="azcli-$(date +%Y%m%d%H%M%S)"

docker run \
    --name "${__AX_NAME}" \
    --mount type=volume,source="AzureCLI",target="/root" \
    $__AX_DOCKER_ARGS_INTERACTIVE $__AX_DOCKER_ARGS_ONE_TIME $__AX_DOCKER_ARGS_UP_TO_DATE \
    mcr.microsoft.com/azure-cli
