#! /usr/bin/env zsh

# Start-DockerJupyterNotebook: Start Jupyter Notebook in Docker

source "${0:h}/../lib/output.zsh"
source "${0:h}/../lib/validation.zsh"

[[ "$1" == "--help" ]] && echo "Usage: ${0:t} - Start Jupyter Notebook container mounting current directory" && return 0

__ax_check_deps docker || return 2

source "${0:h}/../lib/docker.zsh"

[[ -f /tmp/jupyternotebook*(.) ]] && rm /tmp/jupyternotebook*

local __AX_NAME="jupyternotebook-$(date +%Y%m%d%H%M%S)"

docker run \
    --name "${__AX_NAME}" \
    --publish 8888:8888 \
    --mount type=bind,source="$(pwd)",target="/home/jovyan/work" \
    $__AX_DOCKER_ARGS_BACKGROUND $__AX_DOCKER_ARGS_ONE_TIME $__AX_DOCKER_ARGS_UP_TO_DATE $__AX_DOCKER_ARGS_RUN_AS_ME \
    quay.io/jupyter/base-notebook > "/tmp/${__AX_NAME}.log"
