#! /usr/bin/env zsh

# Test-TrailingNewline: Check whether text files end with exactly one newline

source "${0:h}/../lib/output.zsh"
source "${0:h}/../lib/validation.zsh"
source "${0:h}/../lib/trailing-newline.zsh"

# Variables --------------------------------------------------------------------
local _synopsis="Synopsis:
    ${0:t} [opts] [directory]

See also:
    ${0:t} --help
"
local _help="Description:
    Check whether text files in a directory tree end with exactly one newline.
    Reports failure when files are missing a final newline or contain
    trailing blank lines.
    Uses fd to discover files (respects .gitignore) and file(1) for
    binary detection.

Usage:
    ${0:t} [opts] [directory]

Options:
    --verbose   List each file as it is processed.
    -e ext      Only process files with this extension (repeatable).
    --all       Include hidden files and ignored files.
    --help      Show this help message.

Arguments:
    directory   Target directory (default: current directory)

Examples:
    ${0:t}                          # Check all files in current directory
    ${0:t} --verbose                # Check and list matching files
    ${0:t} -e nix -e md             # Only check .nix and .md files
    ${0:t} ~/projects               # Check files in specific directory
"


# Functions --------------------------------------------------------------------
_synopsis() {
    echo "${_synopsis}" | tail --lines=+2
}

_help() {
    echo "${_help}" | tail --lines=+2
}


# Options ----------------------------------------------------------------------
local -a _extensions
local _all_flag=""
local _directory=""

while [[ $# -gt 0 ]]; do
    case "$1" in
        --help)     _help_flag=true ;;
        --verbose)  _verbose_flag=true ;;
        --all)      _all_flag=true ;;
        -e)         shift; _extensions+=("$1") ;;
        -*)         __ax_error "Unknown option: $1" && _synopsis && return 1 ;;
        *)          _directory="$1" ;;
    esac
    shift
done


# Main -------------------------------------------------------------------------
[[ -n $_help_flag ]] && _help && return 0

_directory="${_directory:-.}"
__ax_require_dir "$_directory" || return 1
__ax_check_deps fd file || return 2

__ax_trailing_newline_process "check" "$_directory" "$_all_flag" "${_extensions[@]}"
local _rc=$?


# Cleanup ----------------------------------------------------------------------
unfunction _synopsis
unfunction _help

return $_rc
