#! /usr/bin/env zsh

# update-asdfplugin: Update an asdf plugin to the latest version

# Variables --------------------------------------------------------------------
local _synopsis="Synopsis:
    ${0:t} [opts] [args]

See also:
    ${0:t} --help
"
local _help="Description:
    Update asdf plugin to the latest version

Usage:
    ${0:t} [opts] [args]

Options:
    --help      Show this help message.
    --keep      Keep the previous version installed.

Examples:
    ${0:t} bat      # Update the 'bat' asdf plugin to the latest version
    ${0:t} nodejs   # Update the 'nodejs' asdf plugin to the latest version
    ${0:t} --keep R # Update the 'R' asdf plugin and keep the previous version
"


# Functions --------------------------------------------------------------------
_synopsis() {
    echo "${_synopsis}" | tail --lines=+2
}

_help() {
    echo "${_help}" | tail --lines=+2
}


# Options ----------------------------------------------------------------------
while [[ $# -gt 0 ]]; do
    case "$1" in
        --help)     _help_flag=true ;;
        --keep)     _keep_flag=true ;;
        *)          _args=$1         ;;
    esac
    shift
done


# Main -------------------------------------------------------------------------
[[ -n $_help_flag ]] && _help && return 0
[[ -z $_args ]] && echo "Error: Missing plugin name" && return 1


# Driver -----------------------------------------------------------------------
function update_asdfplugin() {
    local arg=${1}

    local current_version=$(asdf current --no-header "${arg}" 2>/dev/null | awk '{print $2}')
    if [[ -z ${current_version} ]]; then
        echo "Error: Plugin '${arg}' is not installed." >&2
        return 1
    fi

    local latest_version=$(asdf latest "${arg}" 2>/dev/null | awk '{print $1}')
    if [[ -z ${latest_version} ]]; then
        echo "Error: Unable to fetch the latest version for '${arg}'." >&2
        return 1
    fi

    asdf install "${arg}" "${latest_version}"
    if [[ -n $_keep_flag ]]; then
        return 0
    else
        echo "Setting '${arg}' to version '${latest_version}'..."
        asdf set --home "${arg}" "${latest_version}"
        echo "Uninstalling version '${current_version}' of '${arg}'..."
        asdf uninstall "${arg}" "${current_version}"
    fi
}


update_asdfplugin "${_args}"


# Cleanup ----------------------------------------------------------------------
unfunction _synopsis
unfunction _help
unfunction update_asdfplugin

