#! /usr/bin/env zsh

# Write-Executable: Write the input to a script and make the script executable

source "${0:h}/../lib/output.zsh"
source "${0:h}/../lib/validation.zsh"

# Help -------------------------------------------------------------------------
if [[ "$1" == "-h" || "$1" == "--help" ]]; then
    cat << EOF
Usage: ${0:t} <filename>

Read input from stdin and write it to a script file adding a zsh shebang at
the top of the file, and making it executable.

Options:
    -h, --help  Show this help message

Examples:
    resolve-gitpathrepository | sed -e 's/^/git clone /' | ${0:t} clone-gitrepository
    echo 'foreach file in *(.); do echo \$file; done' | ${0:t} list-file
EOF
    return 0
fi

# Options ----------------------------------------------------------------------
local _arg=""

while [[ $# -gt 0 ]]; do
    case "$1" in
        *)          _arg=$1 ;;
    esac
    shift
done


# Main -------------------------------------------------------------------------
__ax_require_arg "$_arg" "filename" || return 1
__ax_check_deps chmod || return 2


# Driver -----------------------------------------------------------------------
function write_executable() {
    local filename=${1}
    local content
    
    # Read all input from stdin
    content=$(cat)
    
    # Write shebang and content to file
    {
        echo '#! /usr/bin/env zsh'
        echo
        echo "${content}"
    } > "${filename}"
    
    # Make the file executable
    chmod +x "${filename}"
    
    echo "Created executable script: ${filename}"
}


write_executable "${_arg}"


# Cleanup ----------------------------------------------------------------------
unfunction write_executable
